AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to Setup Sumo Logic Sources and supporting AWS Resources for CloudTrail, ALB, Lambda CloudWatch Logs and CloudWatch Metrics."

Parameters:
  SumoLogicDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  SumoLogicAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  SumoLogicAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  SumoLogicOrganizationId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  RemoveSumoLogicResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  AccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  CollectorName:
    Type: String
    Description: "Provide a Collector Name"
    Default: ""
  SumoLogicAccountID:
    Type: String
    Description: "Provide the Sumo Logic Account ID for trust relationship."
    Default: ""

  CreateMetaDataSource:
    Type: String
    Description: "Yes - Creates Sumo Logic MetaData Source. A common metadata source will be created with the region selected.
                  No - If you already have a MetaData Source configured."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  MetaDataSourceName:
    Type: String
    Description: "Change the MetaData Source name to be created else default name will be used."
    Default: ""
  MetaDataSourceCategory:
    Type: String
    Description: "Provide a source Category for the MetaData Source."
    Default: ""

  CreateCloudWatchMetricsSource:
    Type: String
    Description: "Yes - Creates a Sumo Logic CloudWatch Metrics Source which collects Metrics for multiple Namespaces from the region selected.
                  No - If you already have a CloudWatch Metrics Source collecting ALB metrics."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  CloudWatchMetricsSourceName:
    Type: String
    Description: "Provide a Cloud Watch Metrics Source Name"
    Default: ""
  CloudWatchMetricsNameSpaces:
    Default: "AWS/ApplicationELB, AWS/ApiGateway, AWS/DynamoDB, AWS/Lambda, AWS/RDS, AWS/ECS, AWS/ElastiCache, AWS/ELB, AWS/NetworkELB, AWS/SQS, AWS/SNS"
    Description: "Provide Comma delimited list of the namespaces. Default will be AWS/ApplicationELB, AWS/ApiGateway, AWS/DynamoDB, AWS/Lambda, AWS/RDS, AWS/ECS, AWS/ElastiCache, AWS/ELB, AWS/NetworkELB, AWS/SQS, AWS/SNS."
    Type: String
    AllowedPattern: "(\\s*AWS/(ApplicationELB|ApiGateway|DynamoDB|Lambda|RDS|ECS|ElastiCache|ELB|NetworkELB|SQS|SNS)\\s*(,|$))+"
    ConstraintDescription: "Namespaces should be from provided default list and separated by a ,(for list))"
  ScanInterval:
    Default: 300000
    Description: "Provide the scan interval to fetch metrics into Sumo Logic."
    Type: String
  CloudWatchMetricSourceCategory:
    Type: String
    Description: "Provide a source Category for the CloudWatch Metrics Source."
    Default: ""

  CreateALBLogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic ALB Log Source with provided bucket Name."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  CreateALBS3Bucket:
    Type: String
    Description: "Yes - Create a new S3 bucket in AWS S3.
                  No - Use an existing S3 bucket from AWS S3 which has ALB Logs."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  ALBS3LogsBucketName:
    Type: String
    Description: "Required when Bucket creation Flag = No. Provide an existing bucket name that has ALB logs."
    Default: ""
  ALBS3BucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  ALBLogsSourceName:
    Type: String
    Description: "Provide a ALB Logs Source Name"
    Default: ""
  ALBLogsSourceCategory:
    Type: String
    Description: "Provide a source Category for the ALB Logs Source."
    Default: ""

  CreateCloudTrailLogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Cloud Trail Log Source with provided bucket Name."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  CreateCloudTrailBucket:
    Type: String
    Description: "Yes - Create a new CloudTrail bucket in AWS S3.
                  No - Use an existing CloudTrail bucket from AWS S3 which has CloudTrail Logs."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  CloudTrailLogsBucketName:
    Type: String
    Description: "Required when Bucket creation Flag = No. Provide an Existing bucket name that has CloudTrail logs."
    Default: ""
  CloudTrailBucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  CloudTrailLogsSourceName:
    Type: String
    Description: "Provide a CloudTrail Source Name"
    Default: ""
  CloudTrailLogsSourceCategory:
    Type: String
    Description: "Provide a source Category for the CloudTrail Logs Source."
    Default: ""

  CreateCloudWatchLogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Cloud Watch Log Source."
    Default: 'No'
    AllowedValues:
      - 'Yes'
      - 'No'
  CloudWatchLogsSourceName:
    Type: String
    Description: "Provide a CloudWatch Logs Source Name"
    Default: ""
  CloudWatchLogsSourceCategory:
    Type: String
    Description: "Provide a source Category for the CloudTrail Logs Source."
    Default: ""

  TemplatesBucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Bucket Name for all the nested templates.
  NestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

Conditions:
  # Sources Conditions
  install_metadata_source: !Equals [!Ref CreateMetaDataSource, 'Yes']
  install_cloud_watch_metric_source: !Equals [!Ref CreateCloudWatchMetricsSource, 'Yes']
  install_alb_logs_source: !Equals [!Ref CreateALBLogSource, 'Yes']
  install_cloudtrail_logs_source: !Equals [!Ref CreateCloudTrailLogSource, 'Yes']
  install_cloudwatch_logs_source: !Equals [!Ref CreateCloudWatchLogSource, 'Yes']

  install_collector: !Or
    - !Condition install_metadata_source
    - !Condition install_cloud_watch_metric_source
    - !Condition install_alb_logs_source
    - !Condition install_cloudtrail_logs_source
    - !Condition install_cloudwatch_logs_source

  # Bucket Condition and Trail
  create_alb_bucket: !Equals [!Ref CreateALBS3Bucket, 'Yes']
  create_cloudtrail_bucket: !Equals [!Ref CreateCloudTrailBucket, 'Yes']
  create_target_s3_bucket: !Or
    - !Condition create_alb_bucket
    - !Condition create_cloudtrail_bucket

  # SNS
  create_cloudtrail_sns_topic: !And
    - !Not [!Condition create_cloudtrail_bucket]
    - !Condition install_cloudtrail_logs_source
  create_alb_sns_topic: !And
    - !Not [!Condition create_alb_bucket]
    - !Condition install_alb_logs_source

  # Sumo Logic Role
  install_sumo_logic_role: !Or
    - !Condition install_metadata_source
    - !Condition install_cloud_watch_metric_source
    - !Condition install_alb_logs_source
    - !Condition install_cloudtrail_logs_source

Mappings:
  # Bucket names where the Lambda Zip and Nested Templates are kept. Buckets are present in region, with region as suffix.
  # Some buckets names have 's' in the region suffix. It is kept intentional as bucket names were not available.
  # Buckets names which are intentional -
  # 1. appdevzipfiles-eu-north-1s
  # 2. appdevzipfiles-ap-east-1s
  # 3. appdevzipfiles-af-south-1s
  # 4. appdevzipfiles-me-south-1s
  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s
  Region2ELBAccountId:
    us-east-1:
      AccountId: "127311923021"
    us-east-2:
      AccountId: "033677994240"
    us-west-1:
      AccountId: "027434742980"
    us-west-2:
      AccountId: "797873946194"
    af-south-1:
      AccountId: "098369216593"
    ca-central-1:
      AccountId: "985666609251"
    eu-central-1:
      AccountId: "054676820928"
    eu-west-1:
      AccountId: "156460612806"
    eu-west-2:
      AccountId: "652711504416"
    eu-south-1:
      AccountId: "635631232127"
    eu-west-3:
      AccountId: "009996457667"
    eu-north-1:
      AccountId: "897822967062"
    ap-east-1:
      AccountId: "754344448648"
    ap-northeast-1:
      AccountId: "582318560864"
    ap-northeast-2:
      AccountId: "600734575887"
    ap-northeast-3:
      AccountId: "383597477331"
    ap-southeast-1:
      AccountId: "114774131450"
    ap-southeast-2:
      AccountId: "783225319266"
    ap-south-1:
      AccountId: "718504428378"
    me-south-1:
      AccountId: "076674570225"
    sa-east-1:
      AccountId: "507241528517"
    us-gov-west-1:
      AccountId: "048591011584"
    us-gov-east-1:
      AccountId: "190560391635"
    cn-north-1:
      AccountId: "638102146993"
    cn-northwest-1:
      AccountId: "037604701340"

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AwsObservabilityLambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                Resource: '*'

  LambdaHelper:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !FindInMap [RegionMap, !Ref 'AWS::Region', bucketname]
        Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.11.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn

Outputs:
  LambdaHelperARN:
    Description: "Sumo Logic Lambda Helper ARN"
    Value: !GetAtt LambdaHelper.Arn
  LambdaRoleARN:
    Description: "Sumo Logic Lambda Helper Role ARN"
    Value: !GetAtt LambdaRole.Arn