AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.2.0: Template to setup the Sumo Logic AWS Inventory Source and Root Cause Explorer app."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dSumoOrganizationId
          - Section1eRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "App Details - Sumo Logic Collector Configuration"
        Parameters:
          - Section2aInstallApp
          - Section2bCollectorName
          - Section2cSumoLogicAccountID

      - Label:
          default: "AWS Inventory Source Details"
        Parameters:
          - Section3aCreateAwsInventorySource
          - Section3bAwsInventorySourceName
          - Section3cNamespaces
          - Section3dInventorySourceCategory

      - Label:
          default: "AWS XRay Source Details"
        Parameters:
          - Section4aCreateAwsXRaySource
          - Section4bAwsXRaySourceName
          - Section4cXraySourceCategory

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section5aParentStackLambdaARN
          - Section5bTemplatesBucketName
          - Section5cNestedTemplateVersion

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dSumoOrganizationId:
        default: "Sumo Logic Organization Id"
      Section1eRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aInstallApp:
        default: "Create AWS Root Cause Explorer App"
      Section2bCollectorName:
        default: "Collector Name"
      Section2cSumoLogicAccountID:
        default: "Sumo Logic Account ID"

      Section3aCreateAwsInventorySource:
        default: "Create Sumo Logic AWS Inventory Source"
      Section3bAwsInventorySourceName:
        default: "Sumo Logic AWS Inventory Source Name"
      Section3cNamespaces:
        default: "Limit Inventory collection to following namespaces"
      Section3dInventorySourceCategory:
        default: "Sumo Logic AWS Inventory Source Category"

      Section4aCreateAwsXRaySource:
        default: "Create Sumo Logic AWS XRay Source"
      Section4bAwsXRaySourceName:
        default: "Sumo Logic AWS XRay Source Name"
      Section4cXraySourceCategory:
        default: "Sumo Logic AWS Xray Source Category"

      Section5aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section5bTemplatesBucketName:
        default: "Nested Templates Bucket Name"
      Section5cNestedTemplateVersion:
        default: "Nested Templates Version"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dSumoOrganizationId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  Section1eRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aInstallApp:
    Type: String
    Description: "Yes - Installs the Root Cause Explorer App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section2bCollectorName:
    Type: String
    Description: "Change the collector name to be created else default name will be used."
    Default: ""
  Section2cSumoLogicAccountID:
    Type: String
    Description: "Provide the Sumo Logic Account ID for trust relationship."
    Default: ""

  Section3aCreateAwsInventorySource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Aws Inventory Source. Choose No to skip Source Creation."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section3bAwsInventorySourceName:
    Type: String
    Description: "Change the Aws Inventory Source name to be created else default name will be used."
    Default: ""
  Section3cNamespaces:
    Default: ""
    Description: "Provide Comma delimited list of the namespaces to collect. For Eg.- AWS/ApplicationELB, AWS/ApiGateway, AWS/DynamoDB, AWS/Lambda, AWS/RDS"
    Type: CommaDelimitedList
  Section3dInventorySourceCategory:
    Type: String
    Description: "Change the Aws Inventory Source Category to be created else default name will be used."
    Default: ""

  Section4aCreateAwsXRaySource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Aws XRay Source. Choose No to skip Source Creation."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section4bAwsXRaySourceName:
    Type: String
    Description: "Change the Aws XRay Source name to be created else default name will be used."
    Default: ""
  Section4cXraySourceCategory:
    Type: String
    Description: "Change the Aws Xray Source Category to be created else default name will be used."
    Default: ""

  Section5aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section5bTemplatesBucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Bucket Name for all the nested templates.
  Section5cNestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

Conditions:

  install_app: !Equals [!Ref Section2aInstallApp, 'Yes']

  install_inventory_source: !Equals [!Ref Section3aCreateAwsInventorySource, 'Yes']

  install_xray_source: !Equals [!Ref Section4aCreateAwsXRaySource, 'Yes']

  install_collector: !Or
    - !Condition install_inventory_source
    - !Condition install_xray_source

Resources:

  sumoOverview:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Overview App Tsat"
      FolderName: !Sub "AWS Observability ${Section5cNestedTemplateVersion} "
      RetainOldAppOnUpdate: true
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      AppJsonS3Url: !Sub "https://${Section5bTemplatesBucketName}.s3.amazonaws.com/aws-observability-versions/${Section5cNestedTemplateVersion}/appjson/Rce-App.json"

  SumoLogicHostedCollector:
    Type: Custom::Collector
    Condition: install_collector
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      CollectorType: Hosted
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      CollectorName: !Ref Section2bCollectorName
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  RootCauseRole:
    Type: AWS::IAM::Role
    Condition: install_collector
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Operations are performed across resources."
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${Section2cSumoLogicAccountID}:root"
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub "${Section1aSumoDeployment}:${Section1dSumoOrganizationId}"
      Path: "/"
      Policies:
        - PolicyName: SumoInventoryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - apigateway:GET
                  - autoscaling:Describe*
                  - cloudfront:GetDistributionConfig
                  - cloudfront:ListDistributions
                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetTrailStatus
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - codedeploy:List*
                  - codedeploy:BatchGet*
                  - dynamodb:Describe*
                  - dynamodb:List*
                  - ec2:Describe*
                  - ecs:Describe*
                  - ecs:List*
                  - elasticache:Describe*
                  - elasticache:List*
                  - elasticfilesystem:Describe*
                  - elasticloadbalancing:Describe*
                  - elasticmapreduce:Describe*
                  - elasticmapreduce:List*
                  - es:Describe*
                  - es:List*
                  - health:Describe*
                  - kinesis:Describe*
                  - kinesis:List*
                  - lambda:List*
                  - mq:Describe*
                  - mq:List*
                  - rds:Describe*
                  - rds:List*
                  - redshift:Describe*
                  - route53:List*
                  - sqs:ListQueues
                  - ses:GetSendStatistics
                  - ses:GetSendQuota
                  - sns:List*
                  - tag:GetResources
                  - tag:GetTagKeys
                  - tag:GetTagValues
                  - xray:BatchGetTraces
                  - xray:Get*
                  - pi:DescribeDimensionKeys
                  - pi:GetResourceMetrics
                Effect: Allow
                Resource: "*"

  InventorySource:
    Type: Custom::AWSSource
    Condition: install_inventory_source
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceType: AwsInventory
      Namespaces: !Ref Section3cNamespaces
      SourceName: !Ref Section3bAwsInventorySourceName
      SourceCategory: !Ref Section3dInventorySourceCategory
      CollectorId: !GetAtt SumoLogicHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      RoleArn: !GetAtt RootCauseRole.Arn

  XraySource:
    Type: Custom::AWSSource
    Condition: install_xray_source
    Properties:
      ServiceToken: !Ref Section5aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceType: AwsXRay
      SourceName: !Ref Section4bAwsXRaySourceName
      SourceCategory: !Ref Section4cXraySourceCategory
      CollectorId: !GetAtt SumoLogicHostedCollector.COLLECTOR_ID
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      RoleArn: !GetAtt RootCauseRole.Arn