AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Version - v2.3.0: Template to setup the ALB app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aAccountAlias
          - Section2bAccountAliasMappingS3URL

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - ALB Source Log Source Configuration"
        Parameters:
          - Section5aALBLogsAPIUrl
          - Section5bALBLogsSourceName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section6aParentStackLambdaARN
          - Section6bTemplatesBucketName
          - Section6cNestedTemplateVersion

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aAccountAlias:
        default: "Alias for AWS Account Identification. Please leave this blank if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."

      Section2bAccountAliasMappingS3URL:
        default: "S3 URL of a CSV file that maps AWS Account IDs to an Account Alias"

      Section3aInstallApp:
        default: "Install Sumo Logic App"

      Section4aCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5aALBLogsAPIUrl:
        default: "Existing Sumo Logic ALB Logs Source API URL"
      Section5bALBLogsSourceName:
        default: "Provide the ALB Logs Source Name for Field Extraction Rule"

      Section6aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section6bTemplatesBucketName:
        default: "Nested Templates Bucket Name"
      Section6cNestedTemplateVersion:
        default: "Nested Templates Version"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
    Default: ""
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]*"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  Section2bAccountAliasMappingS3URL:
    Type: String
    Description: "Required only if you are using CloudFormation StackSets to deploy the solution in multiple AWS accounts."
    Default: ""

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the ALB App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  Section4aCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting ALB Metrics. Provide the existing Sumo Logic ALB Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5aALBLogsAPIUrl:
    Type: String
    Description: "Required when already collecting ALB logs. Provide the existing Sumo Logic ALB Source API URL. Account, region and namespace Fields will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""
  Section5bALBLogsSourceName:
    Type: String
    Description: "Provide a ALB Logs Source Name for Field Extraction Rule."
    Default: ""

  Section6aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section6bTemplatesBucketName:
    Type: String
    AllowedPattern: ".+"
    Description: Bucket Name for all the nested templates.
  Section6cNestedTemplateVersion:
    Type: String
    Description: "Provide the version for the nested templates. Default is the latest version."
    AllowedPattern: ".+"

Conditions:
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_alb_logs_source: !Not [!Equals [!Ref Section5aALBLogsAPIUrl, '']]

  update_alb_metrics_source: !Not [!Equals [!Ref Section4aCloudWatchExistingSourceAPIUrl, '']]

  create_fer: !Or
    - !Condition update_alb_logs_source
    - !Not [!Equals [!Ref Section5bALBLogsSourceName, '']]

Mappings:
  # Bucket names where the Lambda Zip and Nested Templates are kept. Buckets are present in region, with region as suffix.
  # Some buckets names have 's' in the region suffix. It is kept intentional as bucket names were not available.
  # Buckets names which are intentional -
  # 1. appdevzipfiles-eu-north-1s
  # 2. appdevzipfiles-ap-east-1s
  # 3. appdevzipfiles-af-south-1s
  # 4. appdevzipfiles-me-south-1s
  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Operations are performed across resources."
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  LambdaHelper:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !FindInMap [ RegionMap, !Ref 'AWS::Region', bucketname ]
        Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.13.zip"
      MemorySize: 128
      Timeout: 900
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn

  AccountAliasValue:
    Type: Custom::AccountAlias
    Properties:
      ServiceToken: !GetAtt LambdaHelper.Arn
      Region: !Ref "AWS::Region"
      AccountID: !Ref "AWS::AccountId"
      AccountAlias: !Ref Section2aAccountAlias
      AccountAliasMappingS3Url: !Ref Section2bAccountAliasMappingS3URL
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Condition: install_app
    Type: Custom::App
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Alb App"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      FolderName: !Sub "AWS Observability ${Section6cNestedTemplateVersion} "
      RetainOldAppOnUpdate: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      AppJsonS3Url: !Sub "https://${Section6bTemplatesBucketName}.s3.amazonaws.com/aws-observability-versions/${Section6cNestedTemplateVersion}/appjson/Alb-App.json"

  SumoALBLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_logs_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5aALBLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
        namespace: "AWS/ApplicationELB"
        region: !Ref "AWS::Region"
        accountid: !Ref "AWS::AccountId"

  SumoALBMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_alb_metrics_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4aCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !GetAtt AccountAliasValue.ACCOUNT_ALIAS
        accountid: !Ref "AWS::AccountId"

  AlbLogsFieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    DependsOn: AddLoadBalancerField
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityAlbAccessLogsFER"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_alb_logs_source, !Sub "\"${SumoALBLogsUpdateSource.source_name}\"", !Ref Section5bALBLogsSourceName]
          - ")"
      FieldExtractionRuleParseExpression: '| parse "* * * * * * * * * * * * \"*\" \"*\" * * * \"*\"" as Type, DateTime, loadbalancer, Client, Target, RequestProcessingTime, TargetProcessingTime, ResponseProcessingTime, ElbStatusCode, TargetStatusCode, ReceivedBytes, SentBytes, Request, UserAgent, SslCipher, SslProtocol, TargetGroupArn, TraceId
                                            | tolowercase(loadbalancer) as loadbalancer
                                            | fields loadbalancer'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  AddLoadBalancerField:
    Type: Custom::SumoLogicFieldsSchema
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      FieldName: "loadbalancer"
      RemoveOnDeleteStack: false
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_alb_metrics_source
    Value: !GetAtt SumoALBMetricsUpdateSource.source_name
  ExistingLogSourceName:
    Description: "Existing ALB Logs Source Name"
    Condition: update_alb_logs_source
    Value: !GetAtt SumoALBLogsUpdateSource.source_name