AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to setup the ElastiCache app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aAccountAlias

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - CloudTrail Log Source Configuration"
        Parameters:
          - Section5aCloudTrailLogsAPIUrl
          - Section5bCloudTrailLogsSourceName

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section6aParentStackLambdaARN

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aAccountAlias:
        default: "Alias for AWS Account Identification"

      Section3aInstallApp:
        default: "Install Sumo Logic App"

      Section4aCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5bCloudTrailLogsSourceName:
        default: "Sumo Logic CloudTrail Logs Source Name"
      Section5aCloudTrailLogsAPIUrl:
        default: "Existing Sumo Logic CloudTrail Logs Source API URL"

      Section6aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"

Parameters:
  Section1aSumoDeployment:
    Type: String
    Default: ""
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the Amazon ElastiCache App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  Section4aCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting Amazon ElastiCache Metrics. Provide the existing Sumo Logic Amazon ElastiCache Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5bCloudTrailLogsSourceName:
    Type: String
    Description: Change the CloudTrail Source name to be created else default name will be used.
    Default: ""
  Section5aCloudTrailLogsAPIUrl:
    Type: String
    Description: "Required when already collecting CloudTrail logs. Provide the existing Sumo Logic CloudTrail Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section6aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.

Conditions:
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_cloudtrail_logs_source: !Not [!Equals [!Ref Section5aCloudTrailLogsAPIUrl, '']]

  update_metrics_source: !Not [!Equals [!Ref Section4aCloudWatchExistingSourceAPIUrl, '']]

  create_fer: !Or
    - !Condition update_cloudtrail_logs_source
    - !Not [!Equals [!Ref Section5bCloudTrailLogsSourceName, '']]

Resources:

  MetricRule:
    Type: Custom::SumoLogicMetricRules
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      RemoveOnDeleteStack: false
      MetricRuleName: "AwsObservabilityElastiCacheMetricsEntityRule"
      MatchExpression: "Namespace=AWS/ElastiCache CacheClusterId=*"
      ExtractVariables:
        entity: "$CacheClusterId._1"
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability ElastiCache App"
      Version: "V1.0.1"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      FolderName: "Sumo Logic AWS Observability Apps "
      RetainOldAppOnUpdate: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  SumoCloudTrailLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_cloudtrail_logs_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5aCloudTrailLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2aAccountAlias

  SumoMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_metrics_source
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1dRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4aCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2aAccountAlias

  FieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityElastiCacheCloudTrailLogsFER"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_cloudtrail_logs_source, !Sub "\"${SumoCloudTrailLogsUpdateSource.source_name}\"", !Ref Section5bCloudTrailLogsSourceName]
          - " (\"elasticache.amazonaws.com\"))"
      FieldExtractionRuleParseExpression: 'json "eventSource", "awsRegion", "requestParameters.cacheClusterId", "responseElements.cacheClusterId" as eventSource, region, req_cacheClusterId, res_cacheClusterId nodrop
                                           | where eventSource = "elasticache.amazonaws.com"
                                           | if (!isEmpty(req_cacheClusterId), req_cacheClusterId, res_cacheClusterId) as cacheclusterid
                                           | "aws/elasticache" as namespace
                                           | fields region, namespace, cacheclusterid'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  AddCacheClusterIdField:
    Type: Custom::SumoLogicFieldsSchema
    Properties:
      ServiceToken: !Ref Section6aParentStackLambdaARN
      FieldName: "cacheclusterid"
      RemoveOnDeleteStack: false
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_metrics_source
    Value: !GetAtt SumoMetricsUpdateSource.source_name
  ExistingLogSourceName:
    Description: "Existing CloudTrail Logs Source Name"
    Condition: update_cloudtrail_logs_source
    Value: !GetAtt SumoCloudTrailLogsUpdateSource.source_name