name: "CF template tests"

on:
  push:
    paths:
    - aws-observability

jobs:
  ValidateCF:
    name: "Cloud Formation template validation"
    runs-on: ubuntu-latest
    steps:
      - run: aws cloudformation validate-template --template-body $GITHUB_WORKSPACE/aws-observability/templates/sumologic_observability.master.template.yaml

  ValidateLinting:
    name: "Cloud Formation template linting verification"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t $GITHUB_WORKSPACE/aws-observability/templates/sumologic_observability.master.template.yaml

  CFSecurityChecksCheckovt:
    name: "Cloud Formation template tests using checkov"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: bridgecrewio/checkov-action@master
        with:
          file: $GITHUB_WORKSPACE/aws-observability/templates/sumologic_observability.master.template.yaml
          quiet: false
          framework: cloudformation
          output_format: cli
          output_bc_ids: true

  CFSecurityChecksCFNNAG:
    name: "cfn-nag for Cloud Formation template"
    runs-on: "ubuntu-latest"
    steps:
      - uses: stelligent/cfn_nag@master
        with:
          input_path: templates


  ValidatePython:
    name: "Validate Python test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: bridgecrewio/checkov-action@master
        with:
          file: $GITHUB_WORKSPACE/aws-observability/templates/sumologic_observability.master.template.yaml
          quiet: false
          framework: python
          output_format: cli
          output_bc_ids: true